### ISSUE TITLE
Erlang release creation with reltool will pull in all possible dependencies automatically

### ISSUE THREAD

**Issue by okeuday** [benoitc/erlang-metrics#6]
When using reltool, xref is used to discover all modules and use that information to pull in all the applications that contain the modules which could easily be a larger set than is defined by the Erlang/OTP .app file `applications` dependency list.  You probably want to make the module use undiscoverable by xref through the indirection of a local module function call that is never inlined.  I have an example of this change that I did for `nodefinder` to prevent `lhttpc` and `hackney` from being pulled in by default (https://github.com/okeuday/nodefinder/commit/46bf7793df919b398f449a8be08663aa1ba8d1fa).  My understanding is that releases built by relx will not require this change, due to only using the `applications` dependency list.

**Comment by benoitc** [comment]
@okeuday Sorry for the late answer. I'm not sure to understand the whole issue. which modules to hide? How to reproduce what you experiment?  Any setting for xref?

**Comment by okeuday** [comment]
@benoitc Modules related to any external dependency that erlang-metrics uses (so all its dependencies).  Building a release with reltool that happens to have all erlang-metrics dependencies present should put all of the dependencies into a release, unless you hide modules this way.  The usage of xref in reltool is embedded, so it doesn't require extra configuration, just a reltool release.

**Comment by benoitc** [comment]
@okeuday oh i see. I will fix it today.
